// <auto-generated />
using System;
using CasaTimo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasaTimo.Infrastructure.Migrations;

[DbContext(typeof(CasaTimoDbContext))]
partial class CasaTimoDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("CasaTimo.Core.Models.Bill", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<decimal>("Amount")
                .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.Property<DateTime>("DueDate")
                .HasColumnType("TEXT");

            b.Property<string>("EmailId")
                .HasColumnType("TEXT");

            b.Property<bool>("IsPaid")
                .HasColumnType("INTEGER");

            b.Property<string>("Issuer")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("PdfPath")
                .HasColumnType("TEXT");

            b.Property<DateTime?>("PeriodFrom")
                .HasColumnType("TEXT");

            b.Property<DateTime?>("PeriodTo")
                .HasColumnType("TEXT");

            b.Property<int>("Type")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.ToTable("Bills");
        });

        modelBuilder.Entity("CasaTimo.Core.Models.ConnectorConfig", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("ConnectorName")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("SettingsJson")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<DateTime>("UpdatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.HasKey("Id");

            b.ToTable("ConnectorConfigs");
        });

        modelBuilder.Entity("CasaTimo.Core.Models.Device", b =>
        {
            b.Property<string>("Id")
                .HasColumnType("TEXT");

            b.Property<bool>("IsActive")
                .HasColumnType("INTEGER");

            b.Property<string>("Location")
                .HasColumnType("TEXT");

            b.Property<string>("Name")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("Type")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.ToTable("Devices");
        });

        modelBuilder.Entity("CasaTimo.Core.Models.MaintenanceRecord", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<decimal?>("Cost")
                .HasColumnType("TEXT");

            b.Property<DateTime>("Date")
                .HasColumnType("TEXT");

            b.Property<string>("Description")
                .HasColumnType("TEXT");

            b.Property<string>("DeviceId")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<DateTime?>("NextDueDate")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("DeviceId");

            b.ToTable("MaintenanceRecords");
        });

        modelBuilder.Entity("CasaTimo.Core.Models.Reminder", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<long>("BillId")
                .HasColumnType("INTEGER");

            b.Property<int>("DaysBefore")
                .HasColumnType("INTEGER");

            b.Property<DateTime>("DueDate")
                .HasColumnType("TEXT");

            b.Property<bool>("IsSent")
                .HasColumnType("INTEGER");

            b.Property<string>("Message")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("BillId");

            b.ToTable("Reminders");
        });

        modelBuilder.Entity("CasaTimo.Core.Models.SensorReading", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("DeviceId")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("Metric")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<DateTime>("Timestamp")
                .HasColumnType("TEXT");

            b.Property<string>("Unit")
                .HasColumnType("TEXT");

            b.Property<double>("Value")
                .HasColumnType("REAL");

            b.HasKey("Id");

            b.HasIndex("DeviceId");

            b.HasIndex("Timestamp");

            b.ToTable("SensorReadings");
        });

        modelBuilder.Entity("CasaTimo.Core.Models.MaintenanceRecord", b =>
        {
            b.HasOne("CasaTimo.Core.Models.Device", "Device")
                .WithMany()
                .HasForeignKey("DeviceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Device");
        });

        modelBuilder.Entity("CasaTimo.Core.Models.Reminder", b =>
        {
            b.HasOne("CasaTimo.Core.Models.Bill", "Bill")
                .WithMany()
                .HasForeignKey("BillId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Bill");
        });

        modelBuilder.Entity("CasaTimo.Core.Models.SensorReading", b =>
        {
            b.HasOne("CasaTimo.Core.Models.Device", "Device")
                .WithMany()
                .HasForeignKey("DeviceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Device");
        });

        modelBuilder.Entity("CasaTimo.Core.Models.PushSubscription", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("Endpoint")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<string>("P256dh")
                .HasColumnType("TEXT");

            b.Property<string>("Auth")
                .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            b.HasKey("Id");

            b.HasIndex("Endpoint")
                .IsUnique();

            b.ToTable("PushSubscriptions");
        });
#pragma warning restore 612, 618
    }
}
